/* Rendering, navigation and dialog behavior shared by all site pages. */
window.SigamizUI=(()=>{
 const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const formatPrice=value=>new Intl.NumberFormat('uz-UZ').format(Number(value||0))+" so'm";
 const photoFor=item=>item.photos?.[0]||'';
 const titleFor=item=>[item.district,item.university].filter(Boolean).join(', ')||'Toshkent';
 const phone=value=>String(value||'').replace(/[^0-9+]/g,'');
 const parseDate=value=>{if(!value)return null;let text=String(value).replace(' ','T');if(!/[zZ]|[+-]\d\d:\d\d$/.test(text))text+='Z';const date=new Date(text);return isNaN(date)?null:date;};
 const publishedLabel=value=>{const date=parseDate(value);if(!date)return "Yangi e'lon";const days=Math.max(0,Math.floor((Date.now()-date)/86400000));return days?`${days} kun oldin joylandi`:'Bugun joylandi';};
 const expiresLabel=value=>{const date=parseDate(value);if(!date)return '';const days=Math.ceil((date-Date.now())/86400000);return days<=0?'Muddati tugagan':`${days} kun qoldi`;};
 const authorName=item=>item.author_first_name||(item.telegram_username?'@'+String(item.telegram_username).replace(/^@/,''):'Telegram foydalanuvchi');
 const authorHtml=(item,extra='')=>`<div class="author-row author ${extra}"><span class="avatar">${item.author_photo_url?`<img src="${escapeHtml(item.author_photo_url)}" alt="">`:escapeHtml(authorName(item).replace(/^@/,'').slice(0,1).toUpperCase())}</span><div><b>${escapeHtml(authorName(item))}</b><span>${escapeHtml([item.telegram_username?'@'+item.telegram_username.replace(/^@/,''):'Telegram akkaunt',publishedLabel(item.created_at),expiresLabel(item.expires_at)].filter(Boolean).join(' · '))}</span></div></div>`;
 let catalogPromise;const amenityLabels={};
 function config(){return catalogPromise ||= fetch('/api/config').then(r=>{if(!r.ok)throw Error('Sozlamalar yuklanmadi');return r.json();}).then(data=>{data.catalogs.amenities.forEach(([,label,column])=>amenityLabels[column]=label);return data;}).catch(error=>{catalogPromise=null;throw error;});}
 function tagsFor(item,limit=5){return Object.entries(amenityLabels).filter(([key])=>item[key]).slice(0,limit).map(([,label])=>`<span class="tag">${escapeHtml(label)}</span>`).join('');}
 async function updateBotLinks(){const data=await config().catch(()=>({}));if(!data.bot_username)return;document.querySelectorAll('[data-bot-start]').forEach(link=>link.href=`https://t.me/${encodeURIComponent(data.bot_username)}?start=${encodeURIComponent(link.dataset.botStart||'start')}`);}
 function state(target,mode,retry){const container=document.getElementById(target);if(!container)return;let status=document.getElementById(target+'Status');if(!status){status=document.createElement('div');status.id=target+'Status';container.before(status);}status.className='ui-state '+mode;status.setAttribute('role',mode==='error'?'alert':'status');status.replaceChildren();if(mode==='ready'){status.hidden=true;return;}status.hidden=false;status.append(document.createTextNode(mode==='loading'?'E’lonlar yuklanmoqda…':mode==='empty'?'Hali saqlangan e’lon yo‘q.':'Ma’lumotni yuklab bo‘lmadi.'));if(mode==='error'){const button=document.createElement('button');button.textContent='Qayta urinish';button.onclick=retry;status.append(' ',button);}if(mode==='empty'){const link=document.createElement('a');link.href='/xarita';link.textContent='Xaritadan joy topish →';status.append(' ',link);}}
 let savedFocus=null, inertNodes=[];
 function openDialog(drawer,returnTarget){savedFocus=returnTarget||document.activeElement;drawer.setAttribute('role','dialog');drawer.setAttribute('aria-modal','true');drawer.setAttribute('aria-label',"E'lon tafsilotlari");drawer.tabIndex=-1;inertNodes=[...document.body.children].filter(el=>el!==drawer&&!['SCRIPT','STYLE','SVG'].includes(el.tagName)).map(el=>[el,el.inert]);inertNodes.forEach(([el])=>el.inert=true);document.body.style.overflow='hidden';drawer.querySelector('.close')?.setAttribute('aria-label','Yopish');(drawer.querySelector('.close')||drawer).focus();}
 function closeDialog(drawer){inertNodes.forEach(([el,previous])=>el.inert=previous);inertNodes=[];document.body.style.overflow='';drawer.removeAttribute('aria-modal');savedFocus?.focus();}
 function gallery(media,photos){if(photos.length<2)return;let index=0;const image=media.querySelector('img');const controls=document.createElement('div');controls.className='gallery-controls';const previous=document.createElement('button'),next=document.createElement('button'),count=document.createElement('span');previous.textContent='←';next.textContent='→';previous.setAttribute('aria-label','Oldingi rasm');next.setAttribute('aria-label','Keyingi rasm');count.setAttribute('aria-live','polite');function update(delta){index=(index+delta+photos.length)%photos.length;image.src=photos[index];image.alt=`Xona rasmi ${index+1}`;count.textContent=`${index+1} / ${photos.length}`;}previous.onclick=()=>update(-1);next.onclick=()=>update(1);controls.append(previous,count,next);media.append(controls);update(0);}
 document.addEventListener('keydown',event=>{const drawer=document.getElementById('detailDrawer');if(!drawer?.classList.contains('open'))return;if(event.key==='Escape'){event.preventDefault();window.closeDetail();}if(event.key==='Tab'){const targets=[...drawer.querySelectorAll('a[href],button:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=targets[0],last=targets.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===drawer)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
 document.addEventListener('DOMContentLoaded',()=>{
  const routes=[['/xarita','Xarita'],['/favorites','Saqlanganlar'],['/publish',"E’lon joylash"],['/about','Loyiha haqida']];
  const links=routes.map(([href,label])=>`<a href="${href}"${location.pathname===href?' aria-current="page" class="active"':''}>${label}</a>`).join('');
  const root=document.querySelector('.topbar .nav-inner,.topbar .topbar-inner');
  const nav=root?.querySelector('.nav,.nav-links');if(nav)nav.innerHTML=links;
  if(root){const button=document.createElement('button');button.className='site-menu-button';button.textContent='Menyu';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','siteMenu');const menu=document.createElement('nav');menu.id='siteMenu';menu.className='site-mobile-menu';menu.setAttribute('aria-label','Asosiy menyu');menu.innerHTML=links;root.append(button);document.body.append(menu);button.onclick=()=>{const open=menu.classList.toggle('open');button.setAttribute('aria-expanded',String(open));};document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.classList.remove('open');button.setAttribute('aria-expanded','false');}});document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==button){menu.classList.remove('open');button.setAttribute('aria-expanded','false');}});}
  function linkCards(){document.querySelectorAll('article[onclick]').forEach(card=>{const title=card.querySelector('h2,h3');const id=card.dataset.id;if(!title||!id||title.querySelector('a'))return;const anchor=document.createElement('a');anchor.href='/xarita?listing='+encodeURIComponent(id);anchor.textContent=title.textContent;title.replaceChildren(anchor);if(location.pathname==='/xarita')anchor.onclick=e=>{e.preventDefault();e.stopPropagation();window.openDetail(Number(id));};});}
  new MutationObserver(linkCards).observe(document.body,{childList:true,subtree:true});linkCards();
 });
 return {escapeHtml,formatPrice,photoFor,titleFor,phone,parseDate,publishedLabel,expiresLabel,authorName,authorHtml,tagsFor,updateBotLinks,config,state,openDialog,closeDialog,gallery};
})();
