name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Restart and verify
        run: |
          cd /home/admn/sigamiz && git pull
          for service in klapa-bot klapa-backend; do
            echo "Restarting $service..."
            sudo systemctl restart "$service"
            # Ждем завершения запуска сервиса
            sleep 5
            # Проверяем, что сервис активен
            if ! systemctl is-active --quiet "$service"; then
              echo "Error: $service failed to start!"
              exit 1
            fi
          done
